// Generated by CoffeeScript 1.10.0
(function() {
  var sys = require('sys')

  env = null
  desc('this is default task');
  task('default', ['run'], {async: true}, function() {
    return console.log('complete')
  });

  desc('build package， 文件打包到pkg文件夹')
  task('package', {async: true}, function(){
    packageTask('package', 'v0.1', function(){
      var excludeFileList = [
          ,'*.sh'
          ,'readme.md',
          ,'node_modules'
          ,'public/components'
          ,'pkg'
        ];

      this.packageFiles.include('**');
      this.packageFiles.exclude(excludeFileList);
      this.needTarGz = true;

      console.log('========文件压缩完毕======')
      return complete()
    })
    jake.Task["package"].invoke()
  })


  desc('deploy remote 把部署文件拷到服务器，然后在跑jake的启动项目命令')
  // task('deploy', ['package'], {async: true}, function(){
  task('deploy', {async: true}, function(){
    // 登录到本地vagrant
    var sshCmd = "ssh vagrant@192.168.33.10 \"node --version\""
      return jake.exec(sshCmd, {printStdout: true}, function(){
        return complete();
      })
  })

  desc('run project')
  task('run', ['compile'], {async: true}, function(){
    var env = process.env.NODE_ENV || "production"
    var cmd = env=='production'? 'pm2 restart':'NODE_ENV=development DEBUG=qy-weixin:* npm start'

    return jake.exec(cmd, {printStdout: true} , function(){
      console.log('project run....');
      return complete();
    })
  })

  desc('compile project')
  task('compile', {async: true}, function(){
    var cmd = 'npm install'
    return jake.exec(cmd, {printStdout: true}, function(){
      console.log('compile done');
      return complete();
    })
  })
}).call(this);
