// Generated by CoffeeScript 1.10.0
(function() {
  var gulp, browserSync, reload, config

  gulp = require('gulp')
  browserSync = require("browser-sync");
  reload = browserSync.reload;

  config = {
    targetFolder: 'app',
    port: 9001
  };

  gulp.task("watch", function() {
    return gulp.watch([config.targetFolder + "/**/*"], reload);
  });

  gulp.task("server", function() {
    browserSync({
      server: {
        baseDir: "" + config.targetFolder
      },
      port: config.port
    });
    return console.log("server start at " + config.port + "...");
  });

  gulp.task("default", ['server', 'watch'], function() {
    return console.log('=======run task=======');
  });
}).call(this);
